version: '2'

services:
  curveball-db:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./backups:/var/log/pg_backups
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
  curveball-quiz:
    image: gunnarholwerda/quiz
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - '../quiz/src/:/usr/local/src/quiz/src'
      - '../quiz/serverless.yml:/usr/local/src/quiz/serverless.yml'
