version: '2'

services:
  curveball-cache:
    image: redis:4.0
    restart: always
    ports: 
      - "6379:6379"
  curveball-realtime:
    image: curveball/realtime
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - '../realtime/src/:/usr/local/src/realtime/src'
      - '../realtime/index.ts:/usr/local/src/realtime/index.ts'
      - './certs/:/etc/ssl/private/'
  curveball-control:
    image: curveball/control
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - '../curveball-control/src/:/usr/local/src/curveball-control/src/'
      - '../curveball-control/assets/:/usr/local/src/curveball-control/assets/'
      - '../curveball-control/environments/:/usr/local/src/curveball-control/environments/'


