version: '2'

services:
  curveball-cache:
    container_name: curveball-cache
    image: redis:4.0
    restart: always
    ports: 
      - "6379:6379"
  curveball-db:
    container_name: curveball-db
    image: postgres:10.4
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db-container/config:/var/log/pg_schema
    environment:
      POSTGRES_DB: curveball
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  curveball-realtime:
    container_name: curveball-realtime
    build: ../realtime
    image: curveball/realtime
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - '../realtime/src/:/usr/local/src/realtime/src'
      - '../realtime/index.ts:/usr/local/src/realtime/index.ts'
      - './certs/:/etc/ssl/private/'
  curveball-control:
    container_name: curveball-control
    build: ../curveball-control
    image: curveball/control
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - '../curveball-control/src/:/usr/local/src/curveball-control/src/'
      - '../curveball-control/assets/:/usr/local/src/curveball-control/assets/'
      - '../curveball-control/environments/:/usr/local/src/curveball-control/environments/'


